sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=upstream-repo-centos-6
  - INSTANCE=upstream-repo-centos-7
  - INSTANCE=upstream-repo-debian-7
    #  - INSTANCE=upstream-repo-debian-8 InSpec fails to recognize that the service is actually enabled
  - INSTANCE=upstream-repo-opensuse-leap
  - INSTANCE=upstream-repo-ubuntu-1404
  - INSTANCE=upstream-repo-ubuntu-1604
  - INSTANCE=epel-centos-6
  - INSTANCE=epel-centos-7
  - INSTANCE=distro-packages-debian-7
  - INSTANCE=distro-packages-debian-8
  - INSTANCE=distro-packages-fedora-latest
  - INSTANCE=distro-packages-opensuse-leap
  - INSTANCE=distro-packages-ubuntu-1404
  - INSTANCE=distro-packages-ubuntu-1604
  - INSTANCE=source-centos-6
  - INSTANCE=source-centos-7
  - INSTANCE=source-debian-7
  - INSTANCE=source-debian-8
  - INSTANCE=source-fedora-latest
  - INSTANCE=source-opensuse-leap
  - INSTANCE=source-ubuntu-1404
  - INSTANCE=source-ubuntu-1604
  - INSTANCE=modules-centos-7
  - INSTANCE=modules-debian-7
  - INSTANCE=modules-debian-8
  - INSTANCE=modules-fedora-latest
  - INSTANCE=modules-opensuse-leap
  - INSTANCE=modules-ubuntu-1404
  - INSTANCE=modules-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - /opt/chefdk/bin/chef exec delivery local all
      env: UNIT_AND_LINT=1
